# -*- coding: utf-8 -*-
"""Cross_Market_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3nMLokbOrzjwavJ0g-5YXxycF1CeVwa

# **Cryptocurrency (CoinGecko API)**
## **Data Collection**
"""

# Data collection from url
data_crypto = []

import requests
import time # avoiding limiting

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

data_crypto

print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

# following columns for ectracting from collected data
# id, symbol, name, current_price, market_cap, market_cap_rank, total_volume, circulating_supply, total_supply, ath, atl, last_updated(just extract date).

filtered_columns = []

for i in data_crypto:
  filtered_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

filtered_columns

print(f"Total data for filtered columns: {len(filtered_columns)}")

import pandas as pd

crypto_df = pd.DataFrame(filtered_columns) #visualizing data in pandas
crypto_df

# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df

"""# **Top Coins Historical Prices**"""

# finding top 5 coins
crypto_df.nsmallest (5, 'market_cap_rank')

# getting data for top coins
#scrolling through the data from the URL And exracting the coins history for last 365 days from the day of running the code.
import requests
import pandas as pd
import time

all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    time.sleep(5)
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

top_coins_df

# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df

"""# **Oil Prices(WTI Crude)**"""

# data collection from github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file

oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df

# saving file as csv file
oil_df.to_csv("oil_prices.csv",index = False)
oil_df

# Jan 2020 - Feb 2026 extracted from all prices and read file
oil_df = pd.read_csv("/content/oil_prices.csv")
oil_df

"""# **Stock Prices (Yahoo Finance API)**"""

# collect following stocks data from Yahoo Finance API

import yfinance as YF
import pandas as pd

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stocks_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stocks_df["^NSEI"].reset_index()
stocks1_df

# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df

# finding nulls from collected data
stocks1_df.isnull().sum()

# remove null for clear undersating
stocks1_df = stocks1_df.dropna()
stocks1_df

# data collected  for IXIC and GSPC similarly ====> codes where written in same line

# "^IXIC"
stocks2_df = stocks_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df

# "^GSPC"
stocks3_df = stocks_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df

# merging all stocks after cleaning nulls and adding column for comparision
stk_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stk_df

"""# **SQL connection**"""

# import and creating database
import sqlite3

conn = sqlite3.connect("cross_mtk.db")
cursor = conn.cursor()

# creating tables for cryptocurrencies

conn.execute("""CREATE TABLE cryptocurrencies
                 (id VARCHAR(50) PRIMARY KEY,
                 symbol VARCHAR(10),
                 name VARCHAR(100),
                 current_price DECIMAL(18, 6),
                 market_cap BIGINT,
                 market_cap_rank INT,
                 total_volume BIGINT,
                 circulating_supply DECIMAL(20, 6),
                 total_supply DECIMAL(20, 6),
                 ath DECIMAL(18, 6),
                 atl DECIMAL(18, 6),
                 date DATE
                 );

                 """)
conn.commit() # apply the changes to the sqlite3

#creating table for Crypto_prices

conn.execute("""CREATE TABLE top_coins
                 (coin_id VARCHAR(50),
                 date DATE,
                 price DECIMAL(18, 6)
                 );

                 """)
conn.commit()

#creating table for Oil_prices

conn.execute("""CREATE TABLE oil_prices
                 (date DATE PRIMARY KEY,
                 price_INR DECIMAL(18, 6)
                 );

                 """)
conn.commit()

#creating table for Stock_prices
conn.execute("""CREATE TABLE stk_prices
                 (date DATE,
                 open DECIMAL(18, 6),
                 high DECIMAL(18, 6),
                 low DECIMAL(18, 6),
                 close DECIMAL(18, 6),
                 volume BIGINT,
                 ticker VARCHAR(20)
                 );

                 """)
conn.commit()

"""# **Pushing data frames in to sqlite3**"""

import sqlite3

conn = sqlite3.connect ("cross_mtk.db")

crypto_df.to_sql ("cryptocurrencies", conn,if_exists = "replace", index = False) # push crypto_df to sqlite
top_coins_df.to_sql ("top_coins", conn,if_exists = "replace", index = False)
oil_df.to_sql ("oil_prices", conn,if_exists = "replace", index = False)
stk_df.to_sql ("stk_prices", conn,if_exists = "replace", index = False)

conn.commit()

# execute SQL query to fetch table names in sqlite_master
tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
print (tables)

"""# **Querries where mentioned in project file**

## **Cryptocurrencies**
"""

# show/read cryptocurrencies table
df = pd.read_sql("SELECT * FROM  cryptocurrencies;", conn)
df

# 1. Find the top 3 cryptocurrencies by market cap.
import sqlite3
import pandas as pd

conn = sqlite3.connect ("cross_mtk.db")

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY market_cap DESC LIMIT 3;", conn)

df

# 2. List all coins where circulating supply exceeds 90% of total supply.

df = pd.read_sql ("SELECT * FROM cryptocurrencies WHERE circulating_supply > (total_supply * 0.9);", conn)

df

# 3. Get coins that are within 10% of their all-time-high (ATH).

df = pd.read_sql ("SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * Ath;", conn)

df

# 4. Find the average market cap rank of coins with volume above $1B.

df = pd.read_sql ("SELECT AVG(market_cap_rank) FROM cryptocurrencies WHERE total_volume > 1000000000;", conn)

df

# 5. Get the most recently updated coin.

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY last_updated DESC LIMIT 1;", conn)

df

"""## **Crypto_Prices (Daily Prices of Top Coins)**"""

df = pd.read_sql("SELECT * FROM  top_coins;", conn)
df

# 1. Find the highest daily price of Bitcoin in the last 365 days.

df = pd.read_sql ("SELECT * FROM top_coins WHERE coin_id = 'bitcoin' AND date >= date('now', '-365 days') ORDER BY Date DESC LIMIT 1;", conn)

df

# 2. Calculate the average daily price of Ethereum in the past 1 year.

df = pd.read_sql ("SELECT AVG(price) FROM top_coins WHERE coin_id = 'ethereum' AND date >= date('now', '-1 year');", conn)

df

# 3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

df = pd.read_sql("SELECT * FROM top_coins WHERE coin_id = 'bitcoin' AND Date BETWEEN '2025-02-01' AND '2026-02-28' ORDER BY Date;", conn)

df

# 4. Find the coin with the highest average price over 1 year.

df = pd.read_sql ("SELECT coin_id, AVG(price) AS avg_price FROM top_coins GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;", conn)

df

# 5. Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026.

df = pd.read_sql ("""SELECT
(SELECT price FROM top_coins WHERE coin_id = 'bitcoin' AND date = '2025-02-24') /
(SELECT price FROM top_coins WHERE coin_id = 'bitcoin' AND date = '2026-02-22') * 100 AS percent_change;""", conn)

df

"""## **Oil_Price**"""

df - pd.read_sql ("SELECT * FROM  oil_prices;", conn)
df

# 1. Find the highest oil price in the last 5 years.

df = pd.read_sql("""SELECT MAX(Price) AS highest_price FROM oil_prices WHERE Date >= ( SELECT substr
(MAX (date), 1, 4) - 5 || '-01-01' FROM oil_prices);""", conn)

df

# 2. Get the average oil price per year.

df = pd.read_sql ("SELECT substr(date, 1, 4) AS year, AVG(price) AS avg_price_per_year FROM oil_prices GROUP BY strftime('%Y', Date);", conn)

df

# 3. Show oil prices during COVID crash (March–April 2020).

df = pd.read_sql ("SELECT * FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-31' ORDER BY date;", conn)

df

# 4. Find the lowest price of oil in the last 10 years.

df = pd.read_sql ("SELECT MIN(price) AS lowest_price FROM oil_prices WHERE date >= (SELECT date('now', '-10 years'));", conn)

df

# 5. Calculate the volatility of oil prices (max-min difference per year).

df = pd.read_sql("SELECT substr(date, 1, 4) AS year, MAX(price) - MIN(price) AS volatility FROM oil_prices GROUP BY strftime('%Y', Date);", conn)

df

"""## **Stock_Prices**"""

df = pd.read_sql("SELECT * FROM  stk_prices;", conn)
df

# 1. Get all stock prices for a given ticker

df = pd.read_sql ("SELECT * FROM stk_prices WHERE Ticker = '^IXIC' or Ticker = '^NSEI' or Ticker = '^GSPC' GROUP by Ticker ORDER BY Date;", conn)

df

# 2. Find the highest closing price for NASDAQ (^IXIC)

df = pd.read_sql ("SELECT MAX(close) AS highest_closing_price FROM stk_prices WHERE ticker = '^IXIC';", conn)

df

# 3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

df = pd.read_sql ("SELECT date, high - low AS price_difference FROM stk_prices WHERE ticker = '^GSPC' ORDER BY price_difference DESC LIMIT 5;", conn)

df

# 4. Get monthly average closing price for each ticker

df = pd.read_sql ("SELECT ticker, strftime('%Y-%m', date) AS month, AVG(close) AS avg_closing_price FROM stk_prices GROUP BY ticker, month ORDER BY ticker, month;", conn)

df

"""# **Joint Querries**"""

# 1. Compare Bitcoin vs Oil average price in 2025.

df = pd.read_sql ("""SELECT 'bitcoin' AS asset,
AVG(price) AS avg_price
FROM top_coins
WHERE coin_id = 'bitcoin'
AND strftime('%Y', date) = '2025'

UNION ALL

SELECT 'OIL' AS asset,
AVG(price) AS avg_price
FROM oil_prices
WHERE strftime('%Y', date) = '2025';

""",conn)

df

# 2. Check if Bitcoin moves with S&P 500 (correlation idea).

df=pd.read_sql("""SELECT
    date(t.date) AS date,
    t.price AS btc_close,
    s.close AS stk_close
FROM top_coins t
LEFT JOIN stk_prices s
    ON date(t.date) = date(s.date)
   AND s.ticker = '^GSPC'
WHERE t.coin_id = 'bitcoin'
ORDER BY date;
""",conn)
df

# 3. Compare Ethereum and NASDAQ daily prices for 2025.

df = pd.read_sql("""
SELECT
    date(t.date) AS date,
    t.price AS eth_price,
    s.close AS nasdaq_close
FROM top_coins t
JOIN stk_prices s
    ON date(t.date) = date(s.date)
WHERE t.coin_id = 'ethereum'
  AND s.ticker = '^IXIC'
  AND strftime('%Y', t.date) = '2025'
ORDER BY date;
""", conn)

df

# 4. Find days when oil price spiked and compare with Bitcoin price change.

df = pd.read_sql ("""
SELECT
    date(o.Date) AS date,
    o.Price AS oil_price,
    t.price AS btc_price
FROM oil_prices o
JOIN top_coins t
    ON date(o.Date) = date(t.Date)
WHERE t.coin_id = 'bitcoin'
ORDER BY date;
""", conn)

df

# 5. Compare top 3 coins daily price trend vs Nifty (^NSEI).

df = pd.read_sql ("""
SELECT
    date(c.Date) AS date,
    c.coin_id AS coins,
    c.price AS coin_prices,
    n.Close AS nifty_close
FROM top_coins c
JOIN stk_prices n
    ON date(c.Date) = date(n.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND n.Ticker = '^NSEI'
ORDER BY date;
""", conn)

df

# 6. Compare stock prices (^GSPC) with crude oil prices on the same dates


df = pd.read_sql("""
SELECT
    date(s.Date) AS date,
    s.Close AS nifty_close,
    o.Price AS oil_price
FROM stk_prices s
JOIN oil_prices o
    ON date(s.Date) = date(o.Date)
WHERE s.Ticker = '^GSPC'
ORDER BY date;
""", conn)

df

# 7. Correlate Bitcoin closing price with crude oil closing price (same date)

df = pd.read_sql("""
SELECT
    date(b.Date) AS date,
    b.price AS btc_price,
    o.Price AS oil_price
FROM top_coins b
JOIN oil_prices o
    ON date(b.Date) = date(o.Date)
WHERE b.coin_id = 'bitcoin'
ORDER BY date;
""", conn)

df

# 8. Compare NASDAQ (^IXIC) with Ethereum price trends

df = pd.read_sql("""
SELECT
    date(e.Date) AS date,
    e.price AS eth_price,
    i.Close AS ixic_close
FROM top_coins e
JOIN stk_prices i
    ON date(e.Date) = date(i.Date)
WHERE e.coin_id = 'ethereum'
  AND i.Ticker = '^IXIC'
ORDER BY date;
""", conn)

df

# 9. Join top 3 crypto coins with stock indices for 2025
df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.coin_id AS crypto,
    t.price AS crypto_price,
    s.Ticker AS index_symbol,
    s.Close AS index_close
FROM top_coins t
JOIN stk_prices s
    ON date(t.Date) = date(s.Date)
WHERE t.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
  AND strftime('%Y', t.Date) = '2025'
ORDER BY date;
""", conn)

df

# 10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    s.Close AS stk_close,
    o.Price AS oil_price
FROM top_coins t
JOIN stk_prices s
    ON date(t.Date) = date(s.Date)
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY date;
""", conn)

df